apiVersion: v1
kind: Service
metadata:
  name: attention-metrics-server
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30012
  selector:
    app: attention-metrics-server
